apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pms-backend.fullname" . }}-db-migrate-{{ .Release.Revision }}
  labels: {{- include "pms-backend.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        {{- include "pms-backend.labels" . | nindent 8 }}
        app.kubernetes.io/component: db-migrate
    spec:
      restartPolicy: Never
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: db-migrate
          image: {{ include "pms-backend.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "dist/apps/db-migrate/src/main.js"]
          securityContext: {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          env: {{- include "pms-backend.env" . | nindent 12 }}
          resources:
            requests: { cpu: 50m, memory: 96Mi }
            limits: { cpu: 500m, memory: 256Mi }
          volumeMounts: [{ name: tmp, mountPath: /tmp }]
      volumes: [{ name: tmp, emptyDir: {} }]
