export const POST_APPROVED_CALCULATION = Symbol('POST_APPROVED_CALCULATION');
export const REVERSE_POSTED_JOURNAL = Symbol('REVERSE_POSTED_JOURNAL');
export const RECONCILE_GENERAL_LEDGER = Symbol('RECONCILE_GENERAL_LEDGER');
export const MANAGE_ACCOUNTING_EVENT = Symbol('MANAGE_ACCOUNTING_EVENT');
export const CERTIFY_OPENING_BALANCES = Symbol('CERTIFY_OPENING_BALANCES');
