packages:
  - "."
  - "apps/*"
  - "libs/*"
  - "packages/*"
allowBuilds:
  protobufjs: false
minimumReleaseAgeExclude:
  - '@grpc/grpc-js@1.14.6'
overrides:
  proxy-addr: ">=2.0.8"
  multer: ">=2.4.0"
  brace-expansion: ">=2.1.7"
  "@grpc/grpc-js": ">=1.14.6"
