export const GET_INVESTMENT_ACCOUNT_SNAPSHOT = Symbol('GET_INVESTMENT_ACCOUNT_SNAPSHOT');
export const MANAGE_INVESTMENT_SUBSCRIPTION = Symbol('MANAGE_INVESTMENT_SUBSCRIPTION');
export const QUERY_INVESTMENT_SUBSCRIPTIONS = Symbol('QUERY_INVESTMENT_SUBSCRIPTIONS');
