export const MANAGE_RECOGNIZED_INCOME=Symbol('MANAGE_RECOGNIZED_INCOME');
export const MANAGE_CHARGE_MATRIX=Symbol('MANAGE_CHARGE_MATRIX');
export const MANAGE_PURIFICATION=Symbol('MANAGE_PURIFICATION');
