import { Decimal } from 'decimal.js';
export type QuotationVerdict='APPROVABLE'|'ALCO_APPROVAL_REQUIRED'|'NOT_VIABLE';
export class EmptyQuotationBasisError extends Error{readonly code='EMPTY_BASIS'}
export class InsufficientQuotationBasisError extends Error{readonly code='INSUFFICIENT_BASIS';constructor(readonly maximumCapacity:string){super('Quotation basis is insufficient')}}
export interface SolveQuotationInput{placementAmount:string;availableBasis:string;projectedGrossRatePercent:string;targetNetRatePercent:string;standardMaxInvestorNisbaPercent:string;maxTanazulAmount:string;availablePerIrrAmount:string;designatedBasis?:boolean}
export function solveQuotationTarget(input:SolveQuotationInput){
 const amount=positive(input.placementAmount,'placementAmount');const capacity=nonNegative(input.availableBasis,'availableBasis');
 if(capacity.isZero())throw new EmptyQuotationBasisError('Quotation basis is empty');if(capacity.lt(amount))throw new InsufficientQuotationBasisError(capacity.toFixed(2));
 const grossRate=positive(input.projectedGrossRatePercent,'projectedGrossRatePercent');const targetRate=positive(input.targetNetRatePercent,'targetNetRatePercent');const maxNisba=bounded(input.standardMaxInvestorNisbaPercent);const tanazul=nonNegative(input.maxTanazulAmount,'maxTanazulAmount');const reserves=nonNegative(input.availablePerIrrAmount,'availablePerIrrAmount');
 const grossProfit=amount.mul(grossRate).div(100);const targetProfit=amount.mul(targetRate).div(100);const standardProfit=grossProfit.mul(maxNisba).div(100);const requiredNisba=targetRate.div(grossRate).mul(100);const rawGap=targetProfit.minus(standardProfit);const supportGap=rawGap.gt(0)?rawGap:new Decimal(0);const supportCapacity=tanazul.plus(reserves);
 const verdict:QuotationVerdict=requiredNisba.lte(maxNisba)?'APPROVABLE':supportGap.lte(supportCapacity)?'ALCO_APPROVAL_REQUIRED':'NOT_VIABLE';
 return{verdict,governance:verdict==='APPROVABLE'?'STANDARD_KEY':verdict==='ALCO_APPROVAL_REQUIRED'?'NON_STANDARD_LEVER_REQUIRES_ALCO':'LEVER_CAPACITY_EXCEEDED',commercialViability:verdict==='NOT_VIABLE'?'TARGET_NOT_REACHABLE':'BASIS_AND_MARGIN_VIABLE',recommendedInvestorNisbaPercent:(requiredNisba.lt(maxNisba)?requiredNisba:maxNisba).toFixed(6),requiredSupportAmount:supportGap.toFixed(2),maximumBasisCapacity:capacity.toFixed(2),segregatedAccountingRequired:Boolean(input.designatedBasis),notice:'Indicative and non-guaranteed rate. Any non-standard key requires ALCO approval.'};
}
function decimal(value:string,name:string){try{const result=new Decimal(value);if(!result.isFinite())throw new Error();return result}catch{throw new TypeError(`${name} must be a decimal`)}}function positive(value:string,name:string){const result=decimal(value,name);if(result.lte(0))throw new RangeError(`${name} must be positive`);return result}function nonNegative(value:string,name:string){const result=decimal(value,name);if(result.lt(0))throw new RangeError(`${name} cannot be negative`);return result}function bounded(value:string){const result=nonNegative(value,'standardMaxInvestorNisbaPercent');if(result.gt(100))throw new RangeError('standardMaxInvestorNisbaPercent cannot exceed 100');return result}
