export const GET_CALCULATION_RUN = Symbol('GET_CALCULATION_RUN');
export const LIST_CALCULATION_RUNS = Symbol('LIST_CALCULATION_RUNS');
export const INITIATE_PROFIT_CALCULATION = Symbol('INITIATE_PROFIT_CALCULATION');
export const SOLVE_QUOTATION=Symbol('SOLVE_QUOTATION');
