import { randomUUID } from 'node:crypto';
import type { Pool, PoolClient } from 'pg';
import type { AllocationPreconditions, AssetAllocationRepository } from '../../modules/pooling/application/manage-asset-allocation.js';
import type { AssetAllocation } from '../../modules/pooling/domain/asset-allocation.js';

export class PostgresAssetAllocationRepository implements AssetAllocationRepository {
  constructor(private readonly pool: Pool) {}
  async allocatedPercentage(assetId:string,from:string,to?:string) { const result=await this.pool.query<{percentage:string}>(`WITH boundaries AS(SELECT $2::date AS point UNION SELECT effective_from FROM pooling.asset_allocation_version WHERE asset_id=$1::uuid AND effective_from<COALESCE($3::date,'infinity'::date)AND COALESCE(effective_to,'infinity'::date)>$2::date)SELECT COALESCE(max((SELECT COALESCE(sum(a.percentage),0)FROM pooling.asset_allocation_version a WHERE a.asset_id=$1::uuid AND a.effective_from<=b.point AND COALESCE(a.effective_to,'infinity'::date)>b.point)),0)::text AS percentage FROM boundaries b`,[assetId,from,to??null]); return result.rows[0]?.percentage??'0'; }
  async preconditions(assetId:string,approvalId?:string):Promise<AllocationPreconditions> { const result=await this.pool.query<{active_anomalies:string[];has_prior:boolean;approval_valid:boolean}>(`SELECT ARRAY(SELECT DISTINCT kind FROM pooling.asset_anomaly WHERE asset_id=$1::uuid AND status='OPEN') AS active_anomalies,EXISTS(SELECT 1 FROM pooling.asset_allocation_version WHERE asset_id=$1::uuid)AS has_prior,EXISTS(SELECT 1 FROM workflow.approval_action WHERE idempotency_key=$2 AND resource_type='ASSET_ALLOCATION' AND resource_id=$1 AND result_state='APPROVED')AS approval_valid`,[assetId,approvalId??null]); const row=result.rows[0]; return {activeAnomalies:(row?.active_anomalies??[]) as AllocationPreconditions['activeAnomalies'],hasPriorAllocation:row?.has_prior??false,approvalValid:row?.approval_valid??false}; }
  async save(value:AssetAllocation,key:string,correlationId?:string):Promise<'CREATED'|'EXISTING'> { const normalizedKey=key.trim(); if(!/^[A-Za-z0-9._:-]{16,128}$/.test(normalizedKey)) throw new TypeError('Allocation idempotency key must contain between 16 and 128 safe characters'); const client=await this.pool.connect(); try { await client.query('BEGIN'); await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`asset-allocation:${value.assetId}`]); const inserted=await client.query<{allocation_id:string}>(`INSERT INTO pooling.asset_allocation_version(allocation_id,asset_id,pool_id,percentage,effective_from,effective_to,justification,approval_id,idempotency_key)VALUES($1::uuid,$2::uuid,$3,$4::numeric,$5::date,$6::date,$7,$8,$9)ON CONFLICT(idempotency_key)DO NOTHING RETURNING allocation_id::text`,[value.allocationId,value.assetId,value.poolId,value.percentage,value.effectiveFrom,value.effectiveTo??null,value.justification,value.approvalId??null,normalizedKey]); if(inserted.rowCount===1){ await client.query(`INSERT INTO integration.outbox_event(event_id,aggregate_type,aggregate_id,event_type,schema_version,correlation_id,payload,occurred_at)VALUES(gen_random_uuid(),'AssetAllocation',$1,'pms.asset.allocation-created.v1',1,$2::uuid,jsonb_build_object('allocationId',$1,'assetId',$3,'poolId',$4,'percentage',$5,'idempotencyKey',$6),clock_timestamp())`,[value.allocationId,correlationId??randomUUID(),value.assetId,value.poolId,value.percentage,normalizedKey]); await client.query('COMMIT'); return 'CREATED'; } const existing=await client.query<{allocation_id:string;asset_id:string;pool_id:string;percentage:string;effective_from:string;effective_to:string|null;justification:string;approval_id:string|null}>(`SELECT allocation_id::text,asset_id::text,pool_id,percentage::text,effective_from::text,effective_to::text,justification,approval_id FROM pooling.asset_allocation_version WHERE idempotency_key=$1 FOR SHARE`,[normalizedKey]); const row=existing.rows[0]; if(!row||row.allocation_id!==value.allocationId||row.asset_id!==value.assetId||row.pool_id!==value.poolId||row.percentage!==value.percentage||row.effective_from!==value.effectiveFrom||row.effective_to!==(value.effectiveTo??null)||row.justification!==value.justification||row.approval_id!==(value.approvalId??null)) throw new Error('Allocation idempotency conflict'); await client.query('COMMIT'); return 'EXISTING'; } catch(error){await client.query('ROLLBACK').catch(()=>undefined);throw error;} finally{client.release();} }
  async history(assetId:string,asOf?:string) { const result=await this.pool.query<any>(`SELECT allocation_id::text,asset_id::text,pool_id,percentage::text,effective_from::text,effective_to::text,justification,approval_id FROM pooling.asset_allocation_version WHERE asset_id=$1::uuid AND($2::date IS NULL OR effective_from<=$2::date AND COALESCE(effective_to,'infinity'::date)>$2::date)ORDER BY effective_from,allocation_id`,[assetId,asOf??null]); return result.rows.map((row):AssetAllocation=>({allocationId:row.allocation_id,assetId:row.asset_id,poolId:row.pool_id,percentage:row.percentage,effectiveFrom:row.effective_from,...row.effective_to?{effectiveTo:row.effective_to}:{},justification:row.justification,...row.approval_id?{approvalId:row.approval_id}:{}})); }
}
