import type{Pool}from'pg';
import type{AdvanceClosingCommand,ClosingWorkflowRepository}from'../../modules/closing-workflow/application/advance-closing-workflow.js';
import type{ClosingQualityEvidence,ClosingStep,ClosingTransitionResult,ClosingWorkflowState}from'../../modules/closing-workflow/domain/closing-workflow.js';
export class ClosingIdempotencyConflictError extends Error{
  constructor(){super('Closing idempotency key was already used with a different command');this.name='ClosingIdempotencyConflictError';}
}
export class PostgresClosingWorkflowRepository implements ClosingWorkflowRepository{
  constructor(private readonly pool:Pick<Pool,'connect'>){}
  async advanceAtomically(command:AdvanceClosingCommand,transition:(state:ClosingWorkflowState,target:ClosingStep,evidence:ClosingQualityEvidence)=>ClosingTransitionResult){const client=await this.pool.connect();let transactionStarted=false;try{await client.query('BEGIN');transactionStarted=true;await client.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`closing.workflow.${command.closingId}`]);const replay=await client.query<{resulting_step:string;resulting_status:string;step_number:number;previous_step:string;same_actor:boolean;same_evidence:boolean}>(`SELECT resulting_step,resulting_status,step_number,previous_step,actor_id=$3 AS same_actor,evidence=$4::jsonb AS same_evidence FROM workflow.closing_step_event WHERE closing_id=$1::uuid AND idempotency_key=$2`,[command.closingId,command.idempotencyKey,command.actorId,JSON.stringify(command.evidence)]);if(replay.rows[0]){const r=replay.rows[0];if(r.resulting_step!==command.targetStep||!r.same_actor||!r.same_evidence)throw new ClosingIdempotencyConflictError();await client.query('COMMIT');transactionStarted=false;return{currentStep:r.resulting_step as ClosingStep,status:r.resulting_status as ClosingWorkflowState['status'],stepNumber:r.step_number,previousStep:r.previous_step as ClosingStep};}const locked=await client.query<{current_step:string;workflow_status:ClosingWorkflowState['status']}>(`SELECT current_step,workflow_status FROM workflow.closing_period WHERE closing_id=$1::uuid FOR UPDATE`,[command.closingId]);const row=locked.rows[0];if(!row)throw new Error('Closing workflow not found');const result=transition({currentStep:row.current_step as ClosingStep,status:row.workflow_status},command.targetStep,command.evidence);await client.query(`INSERT INTO workflow.closing_step_event(closing_id,step_number,previous_step,resulting_step,resulting_status,actor_id,evidence,idempotency_key)VALUES($1::uuid,$2,$3,$4,$5,$6,$7::jsonb,$8)`,[command.closingId,result.stepNumber,result.previousStep,result.currentStep,result.status,command.actorId,JSON.stringify(command.evidence),command.idempotencyKey]);await client.query(`UPDATE workflow.closing_period SET current_step=$2,workflow_status=$3 WHERE closing_id=$1::uuid`,[command.closingId,result.currentStep,result.status]);await client.query('COMMIT');transactionStarted=false;return result;}catch(error){if(transactionStarted)await client.query('ROLLBACK').catch(()=>undefined);throw error;}finally{client.release();}}
}
