BEGIN;
CREATE TABLE IF NOT EXISTS calculation.reserve_policy(pool_id text NOT NULL REFERENCES pooling.pool(pool_id),reserve_type text NOT NULL CHECK(reserve_type IN('PER','IRR')),currency_code text NOT NULL CHECK(currency_code~'^[A-Z]{3}$'),minimum_balance numeric(30,12) NOT NULL CHECK(minimum_balance>=0),maximum_balance numeric(30,12) NOT NULL CHECK(maximum_balance>=minimum_balance),approval_threshold numeric(30,12) NOT NULL CHECK(approval_threshold>=0),effective_from date NOT NULL,effective_until date,created_by text NOT NULL,PRIMARY KEY(pool_id,reserve_type,effective_from),CHECK(effective_until IS NULL OR effective_until>effective_from));
ALTER TABLE calculation.reserve_movement ADD COLUMN IF NOT EXISTS investor_opening_balance numeric(30,12),ADD COLUMN IF NOT EXISTS bank_opening_balance numeric(30,12),ADD COLUMN IF NOT EXISTS investor_movement_amount numeric(30,12),ADD COLUMN IF NOT EXISTS bank_movement_amount numeric(30,12),ADD COLUMN IF NOT EXISTS investor_closing_balance numeric(30,12),ADD COLUMN IF NOT EXISTS bank_closing_balance numeric(30,12),ADD COLUMN IF NOT EXISTS approval_id text REFERENCES workflow.approval_action(idempotency_key);
CREATE OR REPLACE FUNCTION calculation.enforce_reserve_governance()RETURNS trigger LANGUAGE plpgsql AS $$DECLARE policy calculation.reserve_policy%ROWTYPE;movement_date date;target_pool_id text;BEGIN SELECT business_date,pool_id INTO movement_date,target_pool_id FROM calculation.run WHERE run_id=NEW.run_id;SELECT rp.* INTO policy FROM calculation.reserve_policy rp WHERE rp.pool_id=target_pool_id AND rp.reserve_type=NEW.reserve_type AND rp.effective_from<=movement_date AND(rp.effective_until IS NULL OR rp.effective_until>movement_date)ORDER BY rp.effective_from DESC LIMIT 1;IF NOT FOUND THEN RAISE EXCEPTION 'No effective reserve policy for pool and reserve type';END IF;IF NEW.investor_opening_balance IS NULL OR NEW.bank_opening_balance IS NULL OR NEW.investor_movement_amount IS NULL OR NEW.bank_movement_amount IS NULL OR NEW.investor_closing_balance IS NULL OR NEW.bank_closing_balance IS NULL THEN RAISE EXCEPTION 'Reserve investor and bank attribution is required';END IF;IF NEW.investor_opening_balance+NEW.bank_opening_balance<>NEW.opening_balance OR NEW.investor_movement_amount+NEW.bank_movement_amount<>NEW.movement_amount OR NEW.investor_closing_balance+NEW.bank_closing_balance<>NEW.closing_balance OR NEW.investor_closing_balance<>NEW.investor_opening_balance+NEW.investor_movement_amount OR NEW.bank_closing_balance<>NEW.bank_opening_balance+NEW.bank_movement_amount THEN RAISE EXCEPTION 'Reserve ownership conservation invariant failed';END IF;IF NEW.investor_closing_balance<0 OR NEW.bank_closing_balance<0 THEN RAISE EXCEPTION 'Reserve ownership share cannot become negative';END IF;IF abs(NEW.movement_amount)>policy.approval_threshold OR NEW.closing_balance<policy.minimum_balance OR NEW.closing_balance>policy.maximum_balance THEN IF NEW.approval_id IS NULL OR NOT EXISTS(SELECT 1 FROM workflow.approval_action WHERE idempotency_key=NEW.approval_id AND resource_type='RESERVE_MOVEMENT' AND resource_id=NEW.reserve_movement_id::text AND result_state='APPROVED')THEN RAISE EXCEPTION 'Reserve movement requires explicit approval before application';END IF;END IF;RETURN NEW;END;$$;
DROP TRIGGER IF EXISTS reserve_movement_governance ON calculation.reserve_movement;CREATE TRIGGER reserve_movement_governance BEFORE INSERT ON calculation.reserve_movement FOR EACH ROW EXECUTE FUNCTION calculation.enforce_reserve_governance();
CREATE OR REPLACE FUNCTION calculation.reject_reserve_history_mutation()RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'Reserve policies and movements are append-only';END;$$;
DROP TRIGGER IF EXISTS reserve_movement_immutable ON calculation.reserve_movement;CREATE TRIGGER reserve_movement_immutable BEFORE UPDATE OR DELETE ON calculation.reserve_movement FOR EACH ROW EXECUTE FUNCTION calculation.reject_reserve_history_mutation();
DROP TRIGGER IF EXISTS reserve_policy_immutable ON calculation.reserve_policy;CREATE TRIGGER reserve_policy_immutable BEFORE UPDATE OR DELETE ON calculation.reserve_policy FOR EACH ROW EXECUTE FUNCTION calculation.reject_reserve_history_mutation();
COMMIT;
