BEGIN;
CREATE TABLE IF NOT EXISTS reporting.dashboard_item_catalog(audience text NOT NULL CHECK(audience IN('EXECUTIVE','FINANCE','RISK_ALM','SHARIA')),item_code text NOT NULL,display_order smallint NOT NULL CHECK(display_order>0),cdc_reference text NOT NULL,PRIMARY KEY(audience,item_code),UNIQUE(audience,display_order));
INSERT INTO reporting.dashboard_item_catalog(audience,item_code,display_order,cdc_reference)VALUES
('EXECUTIVE','OUTSTANDING',1,'CDC-26.1'),('EXECUTIVE','NET_COLLECTION',2,'CDC-26.1'),('EXECUTIVE','GROSS_NET_REVENUE',3,'CDC-26.1'),('EXECUTIVE','INVESTOR_BANK_PROFIT',4,'CDC-26.1'),('EXECUTIVE','REALIZED_DISTRIBUTED_TARGET_RATE',5,'CDC-26.1'),('EXECUTIVE','MARGIN_BY_PRODUCT_POOL',6,'CDC-26.1'),('EXECUTIVE','PER_IRR_DCR',7,'CDC-26.1'),('EXECUTIVE','WITHDRAWAL_TREND',8,'CDC-26.1'),('EXECUTIVE','ASSET_QUALITY',9,'CDC-26.1'),('EXECUTIVE','BUDGET_ACTUAL',10,'CDC-26.1'),('EXECUTIVE','ALERTS',11,'CDC-26.1'),('EXECUTIVE','CLOSING_STATUS',12,'CDC-26.1'),
('FINANCE','PROFIT_WATERFALL',1,'CDC-26.2'),('FINANCE','ASSET_CONTRIBUTION',2,'CDC-26.2'),('FINANCE','REVENUE_BY_CATEGORY',3,'CDC-26.2'),('FINANCE','CHARGES_LOSSES',4,'CDC-26.2'),('FINANCE','WEIGHTED_BASES',5,'CDC-26.2'),('FINANCE','SHARING_RATIOS',6,'CDC-26.2'),('FINANCE','ANOMALIES_ADJUSTMENTS',7,'CDC-26.2'),('FINANCE','CLOSING_STATUS',8,'CDC-26.2'),('FINANCE','JOURNALS_RECONCILIATIONS',9,'CDC-26.2'),
('RISK_ALM','YIELD_GAPS',1,'CDC-26.3'),('RISK_ALM','MATURITY_LIQUIDITY_GAPS',2,'CDC-26.3'),('RISK_ALM','CONCENTRATION',3,'CDC-26.3'),('RISK_ALM','NON_PERFORMING_ASSETS',4,'CDC-26.3'),('RISK_ALM','PROJECTIONS',5,'CDC-26.3'),('RISK_ALM','STRESS_TESTS',6,'CDC-26.3'),('RISK_ALM','DCR',7,'CDC-26.3'),('RISK_ALM','PER_IRR_COVERAGE',8,'CDC-26.3'),
('SHARIA','POOL_COMPOSITION',1,'CDC-26.4'),('SHARIA','ASSET_COMPLIANCE',2,'CDC-26.4'),('SHARIA','REVENUE_SOURCES',3,'CDC-26.4'),('SHARIA','DEDUCTED_CHARGES',4,'CDC-26.4'),('SHARIA','PURIFICATION',5,'CDC-26.4'),('SHARIA','SHARIA_INCIDENTS',6,'CDC-26.4'),('SHARIA','PARAMETER_CHANGES',7,'CDC-26.4'),('SHARIA','RESERVE_USES',8,'CDC-26.4'),('SHARIA','EXCEPTIONAL_TREATMENTS',9,'CDC-26.4')ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS reporting.dashboard_item_snapshot(audience text NOT NULL,item_code text NOT NULL,pool_id text NOT NULL,business_date date NOT NULL,value jsonb NOT NULL,generated_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(audience,item_code,pool_id,business_date),FOREIGN KEY(audience,item_code)REFERENCES reporting.dashboard_item_catalog(audience,item_code));
CREATE INDEX IF NOT EXISTS dashboard_snapshot_fast_read ON reporting.dashboard_item_snapshot(audience,pool_id,business_date DESC,item_code);
CREATE OR REPLACE FUNCTION reporting.generate_audience_dashboard_snapshots()RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF NEW.workflow_status='CLOSED'AND OLD.workflow_status IS DISTINCT FROM'CLOSED'THEN INSERT INTO reporting.dashboard_item_snapshot(audience,item_code,pool_id,business_date,value)SELECT catalog.audience,catalog.item_code,scope.pool_id,NEW.business_date,jsonb_build_object('itemCode',catalog.item_code,'scopePoolId',scope.pool_id,'businessDate',NEW.business_date,'totalResources',scope.total_resources,'investedAmount',scope.invested_amount,'uninvestedLiquidity',scope.uninvested_liquidity,'distributableProfit',scope.distributable_profit,'closingStatus','CLOSED')FROM reporting.dashboard_item_catalog catalog CROSS JOIN(SELECT snapshot.pool_id,snapshot.total_resources,snapshot.invested_amount,snapshot.uninvested_liquidity,COALESCE(run.distributable_amount,0)distributable_profit FROM pooling.composition_snapshot snapshot LEFT JOIN calculation.run run ON run.pool_id=snapshot.pool_id AND run.business_date=snapshot.business_date WHERE snapshot.business_date=NEW.business_date AND snapshot.certified UNION ALL SELECT'*',sum(snapshot.total_resources),sum(snapshot.invested_amount),sum(snapshot.uninvested_liquidity),sum(COALESCE(run.distributable_amount,0))FROM pooling.composition_snapshot snapshot LEFT JOIN calculation.run run ON run.pool_id=snapshot.pool_id AND run.business_date=snapshot.business_date WHERE snapshot.business_date=NEW.business_date AND snapshot.certified)scope ON CONFLICT DO NOTHING;END IF;RETURN NEW;END;$$;
CREATE TRIGGER audience_dashboard_on_close AFTER UPDATE OF workflow_status ON workflow.closing_period FOR EACH ROW EXECUTE FUNCTION reporting.generate_audience_dashboard_snapshots();
CREATE OR REPLACE FUNCTION reporting.protect_dashboard_compliance_floor()RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'CDC dashboard compliance floor is immutable';END;$$;
CREATE TRIGGER dashboard_catalog_immutable BEFORE UPDATE OR DELETE ON reporting.dashboard_item_catalog FOR EACH ROW EXECUTE FUNCTION reporting.protect_dashboard_compliance_floor();
CREATE TRIGGER dashboard_snapshot_immutable BEFORE UPDATE OR DELETE ON reporting.dashboard_item_snapshot FOR EACH ROW EXECUTE FUNCTION reporting.protect_dashboard_compliance_floor();
COMMIT;
