BEGIN;
CREATE TABLE IF NOT EXISTS reporting.secure_export(export_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),report_type text NOT NULL CHECK(report_type~'^[A-Z][A-Z0-9_]{2,63}$'),format text NOT NULL CHECK(format IN('PDF','XLSX','CSV','API')),scope text NOT NULL CHECK(scope IN('SINGLE','BULK')),status text NOT NULL CHECK(status IN('APPROVED','PENDING_REINFORCED_APPROVAL','GENERATED')),filters jsonb NOT NULL DEFAULT'{}',requester_id text NOT NULL,approved_by text,approved_at timestamptz,generated_by text,generated_at timestamptz,output_manifest jsonb,output_checksum_sha256 text CHECK(output_checksum_sha256~'^[a-f0-9]{64}$'),idempotency_key text NOT NULL UNIQUE,generation_idempotency_key text UNIQUE,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),CHECK(scope='SINGLE' OR status='PENDING_REINFORCED_APPROVAL' OR(approved_by IS NOT NULL AND approved_by<>requester_id)),CHECK(status<>'GENERATED' OR(output_manifest IS NOT NULL AND output_checksum_sha256 IS NOT NULL)));
CREATE TABLE IF NOT EXISTS reporting.secure_export_event(event_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,export_id uuid NOT NULL REFERENCES reporting.secure_export(export_id),action text NOT NULL CHECK(action IN('REINFORCED_APPROVAL','GENERATE')),actor_id text NOT NULL,resulting_status text NOT NULL,idempotency_key text NOT NULL UNIQUE,occurred_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE OR REPLACE FUNCTION reporting.reject_secure_export_event_mutation()RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'Secure export approval history is append-only';END;$$;
CREATE TRIGGER secure_export_event_immutable BEFORE UPDATE OR DELETE ON reporting.secure_export_event FOR EACH ROW EXECUTE FUNCTION reporting.reject_secure_export_event_mutation();
CREATE OR REPLACE FUNCTION reporting.guard_generated_secure_export()RETURNS trigger LANGUAGE plpgsql AS $$BEGIN IF OLD.status='GENERATED'THEN RAISE EXCEPTION 'Generated secure export is immutable';END IF;RETURN NEW;END;$$;
CREATE TRIGGER generated_secure_export_immutable BEFORE UPDATE OR DELETE ON reporting.secure_export FOR EACH ROW EXECUTE FUNCTION reporting.guard_generated_secure_export();
COMMENT ON TABLE reporting.secure_export IS 'FR-43: tokenized secure exports; bulk exports require distinct reinforced approval; generated PDF manifests carry immutable checksums for signing and evidentiary archiving.';
COMMIT;
