export const MANAGE_REGULATORY_REPORT = Symbol('MANAGE_REGULATORY_REPORT');
export const QUERY_TENOR_YIELD_CURVE=Symbol('QUERY_TENOR_YIELD_CURVE');
export const MANAGE_PLANNING_SCENARIO=Symbol('MANAGE_PLANNING_SCENARIO');
export const GENERATE_HISTORICAL_YIELD_FORECAST=Symbol('GENERATE_HISTORICAL_YIELD_FORECAST');
export const QUERY_AUDIENCE_DASHBOARD=Symbol('QUERY_AUDIENCE_DASHBOARD');
export const QUERY_PROFIT_EXPLANATION=Symbol('QUERY_PROFIT_EXPLANATION');
export const MANAGE_SECURE_EXPORT=Symbol('MANAGE_SECURE_EXPORT');
