export const MANAGE_INVESTMENT_PRODUCT = Symbol('MANAGE_INVESTMENT_PRODUCT');
export const MANAGE_PRODUCT_TERMS = Symbol('MANAGE_PRODUCT_TERMS');
export const MANAGE_PRODUCT_REFERENCES = Symbol('MANAGE_PRODUCT_REFERENCES');
