export const GET_EFFECTIVE_CURRENCY = Symbol('GET_EFFECTIVE_CURRENCY');
export const MANAGE_CURRENCY_REFERENCE = Symbol('MANAGE_CURRENCY_REFERENCE');
export const GET_EFFECTIVE_REGULATORY_RULE = Symbol('GET_EFFECTIVE_REGULATORY_RULE');
