import { validateAssetAllocation, type AssetAllocation } from '../domain/asset-allocation.js';
export interface AllocationPreconditions { activeAnomalies: readonly ('SHARIA'|'ACCOUNTING')[]; hasPriorAllocation: boolean; approvalValid: boolean; }
export interface AssetAllocationRepository { allocatedPercentage(assetId:string,effectiveFrom:string,effectiveTo?:string):Promise<string>; preconditions(assetId:string,approvalId?:string):Promise<AllocationPreconditions>; save(allocation:AssetAllocation,idempotencyKey:string,correlationId?:string):Promise<'CREATED'|'EXISTING'>; history(assetId:string,asOf?:string):Promise<readonly AssetAllocation[]>; }
export class ManageAssetAllocation {
  constructor(private readonly repository: AssetAllocationRepository) {}
  async simulate(command: AssetAllocation) { const [current, conditions] = await Promise.all([this.repository.allocatedPercentage(command.assetId,command.effectiveFrom,command.effectiveTo),this.repository.preconditions(command.assetId,command.approvalId)]); const capacity=validateAssetAllocation(command,current); return {...capacity,currentAllocatedPercentage:current,simulated:true,blockingAnomalies:conditions.activeAnomalies,approvalRequired:conditions.hasPriorAllocation&&!conditions.approvalValid,executable:conditions.activeAnomalies.length===0&&(!conditions.hasPriorAllocation||conditions.approvalValid)}; }
  async allocate(command: AssetAllocation, key: string, correlationId?: string) { const [current,conditions] = await Promise.all([this.repository.allocatedPercentage(command.assetId,command.effectiveFrom,command.effectiveTo),this.repository.preconditions(command.assetId,command.approvalId)]); const capacity=validateAssetAllocation(command,current); if(conditions.activeAnomalies.length) throw new Error(`Asset isolated by active ${conditions.activeAnomalies.join(',')} anomaly`); if(conditions.hasPriorAllocation&&!conditions.approvalValid) throw new Error('Reallocation requires an approved and documented decision'); const normalizedKey=key.trim(); if(!/^[A-Za-z0-9._:-]{16,128}$/.test(normalizedKey)) throw new TypeError('Allocation idempotency key must contain between 16 and 128 safe characters'); if(correlationId!==undefined&&!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(correlationId)) throw new TypeError('Allocation correlation identifier must be a UUID'); const status=await this.repository.save(command,normalizedKey,correlationId?.trim().toLowerCase()); return {allocation:command,...capacity,status}; }
  history(assetId:string,asOf?:string) { return this.repository.history(assetId,asOf); }
}
