export const CALCULATE_DCR = Symbol('CALCULATE_DCR');
export const RUN_STRESS_SCENARIO = Symbol('RUN_STRESS_SCENARIO');
export const GET_PUBLISHED_RISK_DASHBOARD = Symbol('GET_PUBLISHED_RISK_DASHBOARD');
