export const MANAGE_INVESTMENT_POOL=Symbol('MANAGE_INVESTMENT_POOL');
export const MANAGE_POOL_COMPOSITION=Symbol('MANAGE_POOL_COMPOSITION');
export const MANAGE_ASSET_ALLOCATION=Symbol('MANAGE_ASSET_ALLOCATION');
export const MANAGE_ASSET_QUALITY=Symbol('MANAGE_ASSET_QUALITY');
